server:
  servlet:
    context-path: /gestao-servicos/api

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gestao-servicos?createDatabaseIfNotExist=true
    username: postgres
    password: 852456
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /public/swagger
