server:
  servlet:
    context-path: /gestao-servicos/api

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/gestao-servicos
    username: postgres
    password: 852456
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html