server:
  servlet:
    context-path: /gestao-servicos/api

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestaoservicos
    username: root
    password: 852456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

springdoc:
  swagger-ui:
    path: /public/swagger

